### ISSUE TITLE
documentation: "," missing after path="<path>"

### ISSUE THREAD

**Issue by SpaceTeddy** [clementprevot/pyduro#13]
Hi Clement,

there is a "," missing in the documentation after path="<path>"

set.run(
  burner_address="<burner IP address>",
  serial="<burner serial number>",
  pin_code="<burner pin code>",
  path="<path>"
  value="<value>"
)

**Comment by clementprevot** [comment]
Fixed in https://github.com/clementprevot/pyduro/commit/b2e6745f95bfd5fd5e294f69d8dbaf44a570af4a

Thank you for noticing and sorry for the delay :-)
