### ISSUE TITLE
how to use this lib

### ISSUE THREAD

**Issue by SpaceTeddy** [clementprevot/pyduro#2]
Hi Clement,
I would like to ask you how to use this python library to get connection or send commants to the Aduro stove. Currently I use nbe-test, but I would like to play around with your tool.

than you,
kr,
chris

**Comment by SpaceTeddy** [comment]
Hi Clement, 
I would like to ask again how to use the python package, because I can not import it in python3.
```
installed with setup:
Package                 Version
----------------------- ---------
...
pyduro-clementprevot    0.0.1
...
```

```
import of package:
Python 3.9.10 (main, Jan 15 2022, 11:48:00) 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyduro-clementprevot
  File "<stdin>", line 1
    import pyduro-clementprevot
                 ^
SyntaxError: invalid syntax
>>> import pyduro
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pyduro'
>>> 
```

any recommendation to use it.

thanks a lot
chris

**Comment by clementprevot** [comment]
Hi Chris

I'm sorry, I missed your previous message.
To be honest, I haven't maintained nor used this embryo of lib for more than a year, so I won't be able to help any further (I'm not even a Python developer, I just play a bit with it 😅)

Hope you will find something

**Comment by clementprevot** [comment]
@SpaceTeddy Good news, I finally finished working on this and it's now working.

You can install the lib from Pypi and check the documentation in the README.md file to use it.

I hope you'll like it.

**Comment by SpaceTeddy** [comment]
dear Clement,

may thanks to update your lib and your really good documentation. This will help the Aduro community a lot.

I tried to install and use your package but using CLI with your pyduro.py file, I get always the following error messages:

`MacBook-Pro-von-Christian pyduro % python3 pyduro.py -b 192.168.0.12 -s xxxxx -p xxxxxxxxxx get operating 
Traceback (most recent call last):
  File "/Users/christian/Documents/development/Aduro/pyduro/pyduro/src/pyduro/pyduro.py", line 9, in <module>
    from actions import ACTIONS, FUNCTIONS, discover, get, set
  File "/Users/christian/Documents/development/Aduro/pyduro/pyduro/src/pyduro/actions/discover.py", line 5, in <module>
    from pyduro.actions import DEFAULT_DISCOVERY_ADDRESS
  File "/Users/christian/Documents/development/Aduro/pyduro/pyduro/src/pyduro/pyduro.py", line 9, in <module>
    from actions import ACTIONS, FUNCTIONS, discover, get, set
  File "/Users/christian/Documents/development/Aduro/pyduro/pyduro/src/pyduro/actions/get.py", line 6, in <module>
    from pyduro.actions import CONSUMPTION_DATA, SETTINGS
ModuleNotFoundError: No module named 'pyduro.actions'; 'pyduro' is not a package`

My environment:
- MacOS 
- python 3.10 via homebrew
- pip3 install pyduro
- clone your repository 
- tried with 'python3 pyduro.py -b 192.168.0.12 -s xxxxx -p xxxxxxxxxx get operating'

any idea why the modules are not found? 

thanks a lot for support

BTW: I've done the same on a raspi with python2 and python3, but unfortunatly the same bahaviour

BTW2: the example.py works fine!

Chris

**Comment by clementprevot** [comment]
@SpaceTeddy I just updated the repo and published a new version of the package on Pypi.
Now you don't need to clone the repository, you can directly use the CLI mode:

```bash
python -m pyduro discover
```

**Comment by SpaceTeddy** [comment]
@clementprevot , I updated the package and it works for MacOS and raspian. 
Thx so much for quick support
