### ISSUE TITLE
Poêle Aduro Hybride Homebridge

### ISSUE THREAD

**Issue by draco1544** [clementprevot/pyduro#3]
Bonjour, j'aimerais savoir si il existe, ou si il est possible de créé un plugin homebridge pour controller un poêle Aduro H3 Lux

merci d'avance

**Comment by clementprevot** [comment]
Bonjour

Désolé je n'en ai aucune idée. Je ne possède aucun produit Apple ni même le Aduro H3 Lux.
J'ai bien peur qu'il vous faille faire comme moi et tenter de reverse ingéniéré les appels effectués par l'application

Bon courage
