### ISSUE TITLE
request for nbtest "raw" mode

### ISSUE THREAD

**Issue by SpaceTeddy** [clementprevot/pyduro#5]
@clementprevot 
nbtest has a "raw" mode where you can add manual functions and payload.
The Aduro smartphone app uses a function mode 11 with payload 001* to get values from the oven.
example:
'python3 ./client.py -a 192.168.0.12 -s xxxxx -p xxxxxxxxxx raw 11 001\*'

'20.6,22.0,-557,61.6,0.0,0,14,0,0,0.0,0.0,0,1,0,0,0,0,0.0,0.0,0.0,0.0,0.0,999,0.00,32.0,13.00,20.0,0.0,100,0.00,0.00,0.0,999.9,0,0.00,28.7,0,59.6,96,0,0.0,0.0,0.0,0.0,,0.00,0,0,0.0,0,0,0.0,0,0.00,0.0,0.0,1,2.5,7,260,10,0,0,0.10,2.5,0,0,260,UPC7160713,5,2,9,11,0,1,30,50,0,0,0,0,0,0,0,0,7,38,50,60,0,0,0.0,558,100/0,15/11-22 22:05:42,0,0,1,0,50,0,800,900,0,0,0,0.0,4,0,0,800.0,0,0,0,0,0,20,80,1,771923,69928,2819626,6821815,180,0,20.6,0'

It would be great if this "raw" mode would be also usable with the pyduro in CLI and python application mode.

thx
Christian

**Comment by clementprevot** [comment]
@SpaceTeddy It's done. And the doc has been updated

```bash
pip install --upgrade pyduro
```

Should install the version 2.0.0

---

You can now run:

```bash
python -m pyduro -b <burner> -s <serial> -p <pin code> raw 11
```

Note that you don't need to pass a payload as it will default to `*`. But if you want you can run

```bash
python -m pyduro -b <burner> -s <serial> -p <pin code> raw 11 "*"
```

Or any other payload you want.

---

> with payload 001*

Actually, the payload is only `*`, `001` being the size of the payload (here, 1 byte)

**Comment by SpaceTeddy** [comment]
@clementprevot 
tested and works like a charm ;)

thank you very much for your really good support and great skills.

chris

**Comment by clementprevot** [comment]
I'm glad it works for you!!

And thank you very much for your support, I really appreciate ❤️!!
