### ISSUE TITLE
Setting variables gives an error

### ISSUE THREAD

**Issue by brjhaverkamp** [clementprevot/pyduro#7]
Hi clemontprevot,

Thanks for this great library. I was looking for a long time to control my Aduro H1 stove localy and not through the cloud.
I downloaded it with pip install pyduro.
Plan is to create a small plugin in domoticz to work with this!

First of all, discovery and getting variables works fine.
But setting variables fails.
I tried several parameters, for example the one in your  description (Of course here I use my IP, serial and password ):
python -m pyduro -b 192.168.1.250 -s 1234 -p 12345678 set settings "misc.start" "1"
usage: PyDuro [-h] [-b BURNER] [-s SERIAL] [-p PIN] [-v] {discover,get,raw,set} ...
PyDuro: error: unrecognized arguments: 1

I tried several syntaxes, but couldn't get it to work.
Am I doing something wrong here, or is this an issue with the new version? Has the syntax changed.

Regards,

Bert Haverkamp

**Comment by brjhaverkamp** [comment]
OK, as it always happens... 5 min after I wrote above issue I found the solution :-)
The right format is now 
set  "boiler.temp" "15"
The syntax for getting the value is 
get  settings "boiler.temp" 

So the only thing needed is to update the documentation:-) and then close this issue.
Thanks again for the great work!

**Comment by clementprevot** [comment]
Hi @brjhaverkamp 

Thank you for opening this issue. Indeed, the error is in the documentation.
Thank you for pointing it out. I will fix it right away.

Have a great day!
