### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by brjhaverkamp** [clementprevot/pyduro#8]
Hi Clemont,

I found an other little documentation correction.
In your set.run example, you still have the argument  function_name in there. But I think in your latest update you took it out.

set.run(
  burner_address="<burner IP address>",
  serial="<burner serial number>",
  pin_code="<burner pin code>",
  function_name="<settings|range|operating|advanced|consumption|chart|logs|info|versions>",
  path="<path>"
  value="<value>"
)
should be

set.run(
  burner_address="<burner IP address>",
  serial="<burner serial number>",
  pin_code="<burner pin code>",
  path="<path>"
  value="<value>"
)

Btw, is there a more direct way to contact you if I have questions or suggestions on the library? 

Kind regards,

Bert Haverkamp

**Comment by clementprevot** [comment]
Hi @brjhaverkamp 

Good catch once again.
In such cases, don't hesitate to directly open a Pull Request to fix the documentation.

And nope, there is no better way to contact me other than the repository.

I will fix the doc. Thank you for opening this issue

Have a great day

**Comment by brjhaverkamp** [comment]
Bonjour Clemont,

Thanks again. And next time I will see if I can pull off opening a pull request:-)
In that respect (not sure if I should open a new ticket for this, but I just try here)
Do you have any insights on how the settings work? I was trying to figure out how to program the time table, but I can't find those settings in the data. Is this stored in the cloud??
I found Setting path: boiler.*
{
  "diff_over": "1",
  "diff_under": "1",
  "ext_off_delay": "1",
  "ext_on_delay": "1",
  "ext_stop_diff": "1.0",
  "ext_stop_temp": "0.0",
  "ext_switch": "0",
  "friday": "111111111111",
  "friday_24": "",
  "min_return": "270",
  "monday": "111111111111",
  "monday_24": "",
  "reduction": "0",
  "saturday": "111111111111",
  "saturday_24": "",
  "sunday": "111111111111",
  "sunday_24": "",
  "temp": "20",
  "thursday": "111111111111",
  "thursday_24": "",
  "timer": "0",
  "tuesday": "111111111111",
  "tuesday_24": "",
  "wednesday": "111111111111",
  "wednesday_24": ""
}
But I don't think this is related to the Timetable function. Or if it is, I have no clue how:-)

**Comment by clementprevot** [comment]
I haven't played with the timetable through this API (I don't even have it on my Aduro H1), so I wont be able to help you.

Sorry.

**Comment by brjhaverkamp** [comment]
You don't have it on your Aduro H1? Are you sure? I have an H1 and I have it. 
In my Aduro app on my Android phone there are 3 modes: Heatlevel, Wanted room temperature and Time Table. (see app)
Don't  you have this?
![Screenshot_2022-12-14-12-35-52-277_com nbe android adurohybrid1](https://user-images.githubusercontent.com/3051118/207667549-eeb63519-0738-410b-8bbd-79381aab86f7.jpg)

**Comment by clementprevot** [comment]
Yeah I have it in the app, but I haven't seen the timetable in the API
through pyduro
